# Generated by Django 3.2 on 2022-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dish',
            field=models.CharField(default='dish', max_length=20),
        ),
    ]
