# Generated by Django 3.2 on 2022-04-06 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0002_blog_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_stamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='dish',
            field=models.CharField(max_length=20),
        ),
    ]
