# Generated by Django 3.2 on 2022-04-07 16:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0003_auto_20220406_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='card',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
